
keycloak:
  auth-server-url: https://auth1.capsifi.com/
  realm: capsifi_dev_tenant
  bearer-only: 'true'
  public-client: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: capsifi_dev_client
  client-key-password: iQENy3rYFu5F0kjEzN4xmXPAUFyXAy3h

keycloak-config:  
  master-realm: master
  admin-client: admin-cli
  user-name: ajain
  user-password: ?f$nCq8R!jny

mail-config:  
  host: smtp.gmail.com
  port: 587
  mailid: sss@ssism.org
  password: Admin@12345
  reset-password-mail-body: Hi %s, %nThis is your new password %s %nPlease use this password to login.%nTeam%nCapsifi
