
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://auth1.capsifi.com/realms/capsifi_dev_tenant
          jwk-set-uri: https://auth1.capsifi.com/realms/capsifi_dev_tenant/protocol/openid-connect/certs


keycloak:
  auth-server-url: https://auth1.capsifi.com/
  realm: capsifi_dev_tenant
  bearer-only: 'true'
  public-client: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: capsifi_dev_client
  client-key-password: iQENy3rYFu5F0kjEzN4xmXPAUFyXAy3h

keycloak-config:
  master-realm: master
  admin-client: admin-cli
  user-name: rvenkatachalapathy
  user-password: Al0cb$WqNmX8c$kT

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
