server:
  port: 6000

spring:
  application:
    name: auth
  jackson:
    default-property-inclusion: NON_NULL
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://auth.capsifi.com/realms/capsifi_dev_tenant
          jwk-set-uri: https://auth.capsifi.com/realms/capsifi_dev_tenant/protocol/openid-connect/certs

keycloak:
  auth-server-url: https://auth.capsifi.com/
  realm: capsifi_dev_tenant
  bearer-only: 'true'
  public-client: 'true'
  use-resource-role-mappings: 'true'
  ssl-required: external
  resource: capsifi_dev_client
  client-key-password: MQkWQTpTpRtOeyx7NqxoQZP1Q4BfLaJy

keycloak-config:  
  master-realm: master
  admin-client: admin-cli
  user-name: ajain
  user-password: 3zEFAH&6bKJe

mail-config:  
  host: smtp.gmail.com
  port: 587
  mailid: sss@ssism.org
  password: Admin@12345
  reset-password-mail-body: Hi %s, %nThis is your new password %s %nPlease use this password to login.%nTeam%nCapsifi dev
