server:
  port: 6000

spring:
  application:
    name: auth
  profiles:
    include:
    - keycloak-config  
  jackson:
    default-property-inclusion: NON_NULL
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://auth1.capsifi.com/realms/capsifi_dev_tenant
          jwk-set-uri: https://auth1.capsifi.com/realms/capsifi_dev_tenant/protocol/openid-connect/certs

