logging:
  level:
    org:
      springframework: INFO
    com:
      capsicum: DEBUG
    root: ERROR
spring:
  application:
    name: dynamic-query-service
  profiles:
    active: local,azdev,prod
timezone: UTC
server:
  port: 8090Updated
  error:
    include-stacktrace: never
