logging:
  level:
    org:
      springframework: INFO
    com:
      capsicum: DEBUG
    root: ERROR
spring:
  application:
    name: dynamic-query-service

timezone: UTC
server:
  port: 8090
  error:
    include-stacktrace: never
